package com.rain.mapper;

import com.rain.entity.*;
import com.rain.util.JdbcUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class LifeServiceMapper {
    public List<Appointment> findAppointmentByPage(Integer userId, String hospitalName, String status, Integer page, Integer size) throws SQLException {
        StringBuilder sql = new StringBuilder("select * from appointment where user_id=?");
        List<Object> params = new ArrayList<>(); params.add(userId);
        if (hospitalName != null && !hospitalName.isEmpty()) { sql.append(" and hospital_name like ?"); params.add("%" + hospitalName + "%"); }
        if (status != null && !status.isEmpty()) { sql.append(" and status=?"); params.add(status); }
        sql.append(" order by create_time desc limit ?,?"); params.add((page - 1) * size); params.add(size);
        try (Connection conn = JdbcUtil.getConnection(); PreparedStatement ps = conn.prepareStatement(sql.toString())) { bind(ps, params); ResultSet rs = ps.executeQuery(); List<Appointment> list = new ArrayList<>(); while (rs.next()) { Appointment a = new Appointment(); a.setId(rs.getInt("id")); a.setUserId(rs.getInt("user_id")); a.setHospitalId(rs.getInt("hospital_id")); a.setHospitalName(rs.getString("hospital_name")); a.setPetName(rs.getString("pet_name")); a.setPetType(rs.getString("pet_type")); a.setConditionDescription(rs.getString("condition_description")); a.setImages(rs.getString("images")); a.setAppointmentDate(rs.getDate("appointment_date")); a.setAppointmentTime(rs.getString("appointment_time")); a.setContactPhone(rs.getString("contact_phone")); a.setStatus(rs.getString("status")); a.setCreateTime(rs.getTimestamp("create_time")); list.add(a);} return list; }
    }
    public Integer countAppointment(Integer userId, String hospitalName, String status) throws SQLException { StringBuilder sql=new StringBuilder("select count(*) num from appointment where user_id=?"); List<Object> params=new ArrayList<>(); params.add(userId); if(hospitalName!=null&&!hospitalName.isEmpty()){sql.append(" and hospital_name like ?");params.add("%"+hospitalName+"%");} if(status!=null&&!status.isEmpty()){sql.append(" and status=?");params.add(status);} try(Connection conn=JdbcUtil.getConnection();PreparedStatement ps=conn.prepareStatement(sql.toString())){bind(ps,params); ResultSet rs=ps.executeQuery(); return rs.next()?rs.getInt("num"):0;}}
    public void updateAppointmentStatus(Integer id,String status) throws SQLException {try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement("update appointment set status=? where id=?")){ps.setString(1,status);ps.setInt(2,id);ps.executeUpdate();}}
    public void cancelAppointment(Integer id) throws SQLException {try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement("delete from appointment where id=?")){ps.setInt(1,id);ps.executeUpdate();}}
    public void addAppointment(Appointment a) throws SQLException {String sql="insert into appointment(user_id,hospital_id,hospital_name,pet_name,pet_type,condition_description,images,appointment_date,appointment_time,contact_phone,status,create_time) values(?,?,?,?,?,?,?,?,?,?,?,now())"; try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql)){ps.setInt(1,a.getUserId());ps.setInt(2,a.getHospitalId());ps.setString(3,a.getHospitalName());ps.setString(4,a.getPetName());ps.setString(5,a.getPetType());ps.setString(6,a.getConditionDescription());ps.setString(7,a.getImages());ps.setDate(8,new java.sql.Date(a.getAppointmentDate().getTime()));ps.setString(9,a.getAppointmentTime());ps.setString(10,a.getContactPhone());ps.setString(11,a.getStatus());ps.executeUpdate();}}

    public List<Insurance> findInsuranceByPage(String insuranceName, String type, Integer page, Integer size) throws SQLException {StringBuilder sql=new StringBuilder("select * from insurance where 1=1"); List<Object>params=new ArrayList<>(); if(insuranceName!=null&&!insuranceName.isEmpty()){sql.append(" and name like ?");params.add("%"+insuranceName+"%");} if(type!=null&&!type.isEmpty()){sql.append(" and type=?");params.add(type);} sql.append(" order by create_time desc limit ?,?"); params.add((page-1)*size);params.add(size); try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql.toString())){bind(ps,params); ResultSet rs=ps.executeQuery(); List<Insurance> list=new ArrayList<>(); while(rs.next()){Insurance i=new Insurance(); i.setId(rs.getInt("id")); i.setName(rs.getString("name")); i.setType(rs.getString("type")); i.setDescription(rs.getString("description")); i.setPremium(rs.getBigDecimal("premium")); i.setCoverageAmount(rs.getBigDecimal("coverage_amount")); i.setDuration(rs.getInt("duration")); i.setSuitablePetType(rs.getString("suitable_pet_type")); i.setCreateTime(rs.getTimestamp("create_time")); list.add(i);} return list;}}
    public Integer countInsurance(String insuranceName,String type) throws SQLException {StringBuilder sql=new StringBuilder("select count(*) num from insurance where 1=1"); List<Object>params=new ArrayList<>(); if(insuranceName!=null&&!insuranceName.isEmpty()){sql.append(" and name like ?");params.add("%"+insuranceName+"%");} if(type!=null&&!type.isEmpty()){sql.append(" and type=?");params.add(type);} try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql.toString())){bind(ps,params); ResultSet rs=ps.executeQuery(); return rs.next()?rs.getInt("num"):0;}}
    public Insurance findInsuranceById(Integer id) throws SQLException {try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement("select * from insurance where id=?")){ps.setInt(1,id); ResultSet rs=ps.executeQuery(); if(rs.next()){Insurance i=new Insurance(); i.setId(rs.getInt("id")); i.setName(rs.getString("name")); i.setType(rs.getString("type")); i.setDescription(rs.getString("description")); i.setPremium(rs.getBigDecimal("premium")); i.setCoverageAmount(rs.getBigDecimal("coverage_amount")); i.setDuration(rs.getInt("duration")); i.setSuitablePetType(rs.getString("suitable_pet_type")); i.setCreateTime(rs.getTimestamp("create_time")); return i;} return null;}}

    public List<InsuranceOrder> findInsuranceOrderByPage(Integer userId, Integer page, Integer size) throws SQLException {String sql="select * from insurance_order where user_id=? order by create_time desc limit ?,?"; try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql)){ps.setInt(1,userId);ps.setInt(2,(page-1)*size);ps.setInt(3,size); ResultSet rs=ps.executeQuery(); List<InsuranceOrder> list=new ArrayList<>(); while(rs.next()){InsuranceOrder x=new InsuranceOrder(); x.setId(rs.getInt("id")); x.setOrderNo(rs.getString("order_no")); x.setUserId(rs.getInt("user_id")); x.setInsuranceId(rs.getInt("insurance_id")); x.setInsuranceName(rs.getString("insurance_name")); x.setPetName(rs.getString("pet_name")); x.setPetType(rs.getString("pet_type")); x.setPetAge(rs.getInt("pet_age")); x.setPetWeight(rs.getBigDecimal("pet_weight")); x.setOwnerName(rs.getString("owner_name")); x.setOwnerPhone(rs.getString("owner_phone")); x.setStatus(rs.getString("status")); x.setTotalAmount(rs.getBigDecimal("total_amount")); x.setCreateTime(rs.getTimestamp("create_time")); list.add(x);} return list; }}
    public Integer countInsuranceOrder(Integer userId) throws SQLException {try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement("select count(*) num from insurance_order where user_id=?")){ps.setInt(1,userId); ResultSet rs=ps.executeQuery(); return rs.next()?rs.getInt("num"):0;}}

    public List<InsuranceClaim> findClaimByPage(Integer userId, Integer page, Integer size) throws SQLException {String sql="select * from insurance_claim where user_id=? order by create_time desc limit ?,?"; try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql)){ps.setInt(1,userId);ps.setInt(2,(page-1)*size);ps.setInt(3,size); ResultSet rs=ps.executeQuery(); List<InsuranceClaim> list=new ArrayList<>(); while(rs.next()){InsuranceClaim c=new InsuranceClaim(); c.setId(rs.getInt("id")); c.setClaimNo(rs.getString("claim_no")); c.setUserId(rs.getInt("user_id")); c.setInsuranceOrderId(rs.getInt("insurance_order_id")); c.setInsuranceName(rs.getString("insurance_name")); c.setPetName(rs.getString("pet_name")); c.setClaimAmount(rs.getBigDecimal("claim_amount")); c.setDescription(rs.getString("description")); c.setEvidenceImages(rs.getString("evidence_images")); c.setStatus(rs.getString("status")); c.setAuditRemark(rs.getString("audit_remark")); c.setCreateTime(rs.getTimestamp("create_time")); list.add(c);} return list;}}
    public Integer countClaim(Integer userId) throws SQLException {try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement("select count(*) num from insurance_claim where user_id=?")){ps.setInt(1,userId); ResultSet rs=ps.executeQuery(); return rs.next()?rs.getInt("num"):0;}}
    public void submitClaim(InsuranceClaim c) throws SQLException {String sql="insert into insurance_claim(claim_no,user_id,insurance_order_id,insurance_name,pet_name,claim_amount,description,evidence_images,status,create_time) values(?,?,?,?,?,?,?,?,?,now())"; try(Connection conn=JdbcUtil.getConnection(); PreparedStatement ps=conn.prepareStatement(sql)){ps.setString(1,c.getClaimNo());ps.setInt(2,c.getUserId());ps.setInt(3,c.getInsuranceOrderId());ps.setString(4,c.getInsuranceName());ps.setString(5,c.getPetName());ps.setBigDecimal(6,c.getClaimAmount());ps.setString(7,c.getDescription());ps.setString(8,c.getEvidenceImages());ps.setString(9,c.getStatus());ps.executeUpdate();}}

    private void bind(PreparedStatement ps, List<Object> params) throws SQLException {for(int i=0;i<params.size();i++) ps.setObject(i+1,params.get(i));}
}
